/** Stable context keys for platform_error_logs (super-admin Error logs UI). */
export const PLATFORM_ERROR_CONTEXT = {
  EMPLOYER_DRIVE_CREATE: 'employer_drive_create',
  EMPLOYER_DRIVE_LIST: 'employer_drive_list',
  EMPLOYER_DRIVE_GET: 'employer_drive_get',
  EMPLOYER_DRIVE_UPDATE: 'employer_drive_update',
  EMPLOYER_DRIVE_CANCEL: 'employer_drive_cancel',
  EMPLOYER_CALENDAR: 'employer_calendar',
  EMPLOYER_PROFILE_READ: 'employer_profile_read',
  EMPLOYER_PROFILE_UPDATE: 'employer_profile_update',
  EMPLOYER_JOB_LIST: 'employer_job_list',
  EMPLOYER_JOB_CREATE: 'employer_job_create',
  EMPLOYER_JOB_UPDATE: 'employer_job_update',
  EMPLOYER_CAMPUS_LIST: 'employer_campus_list',
  EMPLOYER_CAMPUS_REQUEST: 'employer_campus_request',
  EMPLOYER_DASHBOARD: 'employer_dashboard',
  EMPLOYER_APPLICATION_LIST: 'employer_application_list',
  EMPLOYER_APPLICATION_UPDATE: 'employer_application_update',
  CLIENT_API_FAILURE: 'client_api_failure',
  LOGIN_DEBUG: 'login_debug',
  LOGIN_FAILED: 'login_failed',
  SESSION_STALE_SIGNOUT: 'session_stale_signout',
  EMPLOYER_ASSESSMENT_ONLINE_UPDATE: 'employer_assessment_online_update',
  EMPLOYER_ASSESSMENT_CSV_COMMIT: 'employer_assessment_csv_commit',
  AUDIT_LOG_ENTRIES: 'api_audit_log_entries',
  AUDIT_REPORTS: 'api_audit_reports',
  COLLEGE_STUDENT_CV_LIST: 'api_college_student_cv_list',
  STUDENT_CV_LIST: 'api_student_cv_list',
  STUDENT_CV_VIEW: 'api_student_cv_view',
  COLLEGE_STUDENT_CV_VIEW: 'api_college_student_cv_view',
  STUDENT_DASHBOARD: 'api_student_dashboard',
};

/** Human-readable labels for super-admin Error logs filters and detail panel. */
export const PLATFORM_ERROR_CONTEXT_LABELS = {
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_DRIVE_CREATE]: 'Employer — create placement drive',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_DRIVE_LIST]: 'Employer — list placement drives',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_DRIVE_GET]: 'Employer — view placement drive',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_DRIVE_UPDATE]: 'Employer — update placement drive',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_DRIVE_CANCEL]: 'Employer — cancel placement drive',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_CALENDAR]: 'Employer — calendar',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_PROFILE_READ]: 'Employer — read profile',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_PROFILE_UPDATE]: 'Employer — update profile',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_JOB_LIST]: 'Employer — list job postings',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_JOB_CREATE]: 'Employer — create job posting',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_JOB_UPDATE]: 'Employer — update job posting',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_CAMPUS_LIST]: 'Employer — list campuses',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_CAMPUS_REQUEST]: 'Employer — request campus tie-up',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_DASHBOARD]: 'Employer — dashboard',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_APPLICATION_LIST]: 'Employer — applications list',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_APPLICATION_UPDATE]: 'Employer — update application status',
  [PLATFORM_ERROR_CONTEXT.CLIENT_API_FAILURE]: 'Client — API failure (browser report)',
  [PLATFORM_ERROR_CONTEXT.LOGIN_DEBUG]: 'Login — debug trace (browser)',
  [PLATFORM_ERROR_CONTEXT.LOGIN_FAILED]: 'Login — sign-in failed',
  [PLATFORM_ERROR_CONTEXT.SESSION_STALE_SIGNOUT]: 'Session — stale sign-out',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_ASSESSMENT_ONLINE_UPDATE]: 'Employer — online grades update',
  [PLATFORM_ERROR_CONTEXT.EMPLOYER_ASSESSMENT_CSV_COMMIT]: 'Employer — CSV assessment upload commit',
  [PLATFORM_ERROR_CONTEXT.AUDIT_LOG_ENTRIES]: 'Audit — log entries',
  [PLATFORM_ERROR_CONTEXT.AUDIT_REPORTS]: 'Audit — export history',
  [PLATFORM_ERROR_CONTEXT.COLLEGE_STUDENT_CV_LIST]: 'College — student CV list',
  [PLATFORM_ERROR_CONTEXT.STUDENT_CV_LIST]: 'Student — My CVs list',
  [PLATFORM_ERROR_CONTEXT.STUDENT_CV_VIEW]: 'Student — open CV file (S3)',
  [PLATFORM_ERROR_CONTEXT.COLLEGE_STUDENT_CV_VIEW]: 'College — open student CV file (S3)',
  [PLATFORM_ERROR_CONTEXT.STUDENT_DASHBOARD]: 'Student — overview dashboard',
};
