/**
 * Platform academic taxonomy seed — engineering-first defaults for Indian colleges.
 * Seeded by scripts/seed_academic_taxonomy.js after migration 096.
 */

/** @type {Array<{ code: string, name: string, sortOrder?: number }>} */
const TAXONOMY_DEGREE_LEVELS = [
  { code: 'diploma', name: 'Diploma', sortOrder: 10 },
  { code: 'ug', name: 'Undergraduate (UG)', sortOrder: 20 },
  { code: 'pg', name: 'Postgraduate (PG)', sortOrder: 30 },
  { code: 'doctoral', name: 'Doctoral', sortOrder: 40 },
];

/** @type {Array<{ code: string, name: string, levelCode: string, sortOrder?: number, engineeringDefault?: boolean }>} */
const TAXONOMY_DEGREES = [
  { code: 'diploma', name: 'Diploma', levelCode: 'diploma', sortOrder: 10 },
  { code: 'diploma_engineering', name: 'Diploma Engineering', levelCode: 'diploma', sortOrder: 20 },
  { code: 'polytechnic_diploma', name: 'Polytechnic Diploma', levelCode: 'diploma', sortOrder: 30 },
  { code: 'diploma_pharmacy', name: 'Diploma Pharmacy', levelCode: 'diploma', sortOrder: 40 },
  { code: 'diploma_management', name: 'Diploma Management', levelCode: 'diploma', sortOrder: 50 },
  { code: 'diploma_computer_applications', name: 'Diploma Computer Applications', levelCode: 'diploma', sortOrder: 60 },
  { code: 'btech', name: 'B.Tech', levelCode: 'ug', sortOrder: 100, engineeringDefault: true },
  { code: 'be', name: 'B.E.', levelCode: 'ug', sortOrder: 110, engineeringDefault: true },
  { code: 'bca', name: 'BCA', levelCode: 'ug', sortOrder: 120 },
  { code: 'bsc', name: 'B.Sc', levelCode: 'ug', sortOrder: 130 },
  { code: 'bcom', name: 'B.Com', levelCode: 'ug', sortOrder: 140 },
  { code: 'bba', name: 'BBA', levelCode: 'ug', sortOrder: 150 },
  { code: 'ba', name: 'BA', levelCode: 'ug', sortOrder: 160 },
  { code: 'bpharm', name: 'B.Pharm', levelCode: 'ug', sortOrder: 170 },
  { code: 'barch', name: 'B.Arch', levelCode: 'ug', sortOrder: 180 },
  { code: 'bdes', name: 'B.Des', levelCode: 'ug', sortOrder: 190 },
  { code: 'bhm', name: 'BHM', levelCode: 'ug', sortOrder: 200 },
  { code: 'bsw', name: 'BSW', levelCode: 'ug', sortOrder: 210 },
  { code: 'bpt', name: 'BPT', levelCode: 'ug', sortOrder: 220 },
  { code: 'bds', name: 'BDS', levelCode: 'ug', sortOrder: 230 },
  { code: 'mbbs', name: 'MBBS', levelCode: 'ug', sortOrder: 240 },
  { code: 'llb', name: 'LLB', levelCode: 'ug', sortOrder: 250 },
  { code: 'ba_llb', name: 'BA LLB', levelCode: 'ug', sortOrder: 260 },
  { code: 'bba_llb', name: 'BBA LLB', levelCode: 'ug', sortOrder: 270 },
  { code: 'bcom_llb', name: 'B.Com LLB', levelCode: 'ug', sortOrder: 280 },
  { code: 'bed', name: 'B.Ed', levelCode: 'ug', sortOrder: 290 },
  { code: 'bfa', name: 'BFA', levelCode: 'ug', sortOrder: 300 },
  { code: 'bvoc', name: 'B.Voc', levelCode: 'ug', sortOrder: 310 },
  { code: 'mtech', name: 'M.Tech', levelCode: 'pg', sortOrder: 400, engineeringDefault: true },
  { code: 'me_pg', name: 'M.E.', levelCode: 'pg', sortOrder: 410, engineeringDefault: true },
  { code: 'mca', name: 'MCA', levelCode: 'pg', sortOrder: 420, engineeringDefault: true },
  { code: 'mba', name: 'MBA', levelCode: 'pg', sortOrder: 430 },
  { code: 'msc', name: 'M.Sc', levelCode: 'pg', sortOrder: 440 },
  { code: 'mcom', name: 'M.Com', levelCode: 'pg', sortOrder: 450 },
  { code: 'ma', name: 'MA', levelCode: 'pg', sortOrder: 460 },
  { code: 'mpharm', name: 'M.Pharm', levelCode: 'pg', sortOrder: 470 },
  { code: 'march', name: 'M.Arch', levelCode: 'pg', sortOrder: 480 },
  { code: 'mdes', name: 'M.Des', levelCode: 'pg', sortOrder: 490 },
  { code: 'med', name: 'M.Ed', levelCode: 'pg', sortOrder: 500 },
  { code: 'llm', name: 'LLM', levelCode: 'pg', sortOrder: 510 },
  { code: 'msw', name: 'MSW', levelCode: 'pg', sortOrder: 520 },
  { code: 'mph', name: 'MPH', levelCode: 'pg', sortOrder: 530 },
  { code: 'phd', name: 'PhD', levelCode: 'doctoral', sortOrder: 600 },
  { code: 'dsc', name: 'DSc', levelCode: 'doctoral', sortOrder: 610 },
  { code: 'mphil', name: 'MPhil (legacy)', levelCode: 'doctoral', sortOrder: 620 },
];

/** @type {Array<{ code: string, name: string, sortOrder?: number }>} */
const TAXONOMY_DISCIPLINE_CATEGORIES = [
  { code: 'eng_tech', name: 'Engineering & Technology', sortOrder: 10 },
  { code: 'cs_it', name: 'Computer Science & IT', sortOrder: 20 },
  { code: 'ai_data', name: 'AI & Data', sortOrder: 30 },
  { code: 'electronics', name: 'Electronics', sortOrder: 40 },
  { code: 'electrical', name: 'Electrical', sortOrder: 50 },
  { code: 'mechanical', name: 'Mechanical', sortOrder: 60 },
  { code: 'civil', name: 'Civil', sortOrder: 70 },
  { code: 'chemical', name: 'Chemical', sortOrder: 80 },
  { code: 'emerging', name: 'Emerging Technologies', sortOrder: 90 },
  { code: 'management', name: 'Management', sortOrder: 100 },
  { code: 'commerce', name: 'Commerce', sortOrder: 110 },
  { code: 'sciences', name: 'Sciences', sortOrder: 120 },
  { code: 'arts_hum', name: 'Arts & Humanities', sortOrder: 130 },
  { code: 'pharmacy', name: 'Pharmacy', sortOrder: 140 },
  { code: 'law', name: 'Law', sortOrder: 150 },
  { code: 'design', name: 'Design', sortOrder: 160 },
];

/** @type {Array<{ code: string, name: string, categoryCode?: string, sortOrder?: number, engineeringDefault?: boolean }>} */
const TAXONOMY_DISCIPLINES = [
  { code: 'cse', name: 'Computer Science Engineering', categoryCode: 'cs_it', sortOrder: 10, engineeringDefault: true },
  { code: 'it', name: 'Information Technology', categoryCode: 'cs_it', sortOrder: 20, engineeringDefault: true },
  { code: 'ce', name: 'Computer Engineering', categoryCode: 'cs_it', sortOrder: 30, engineeringDefault: true },
  { code: 'se', name: 'Software Engineering', categoryCode: 'cs_it', sortOrder: 40, engineeringDefault: true },
  { code: 'is', name: 'Information Science', categoryCode: 'cs_it', sortOrder: 50, engineeringDefault: true },
  { code: 'ai', name: 'Artificial Intelligence', categoryCode: 'ai_data', sortOrder: 60, engineeringDefault: true },
  { code: 'aiml', name: 'Artificial Intelligence & Machine Learning', categoryCode: 'ai_data', sortOrder: 70, engineeringDefault: true },
  { code: 'ds', name: 'Data Science', categoryCode: 'ai_data', sortOrder: 80, engineeringDefault: true },
  { code: 'da', name: 'Data Analytics', categoryCode: 'ai_data', sortOrder: 90, engineeringDefault: true },
  { code: 'ba_disc', name: 'Business Analytics', categoryCode: 'ai_data', sortOrder: 100 },
  { code: 'ece', name: 'Electronics & Communication Engineering', categoryCode: 'electronics', sortOrder: 110, engineeringDefault: true },
  { code: 'ee_ece', name: 'Electronics Engineering', categoryCode: 'electronics', sortOrder: 120, engineeringDefault: true },
  { code: 'et', name: 'Electronics & Telecommunication', categoryCode: 'electronics', sortOrder: 130, engineeringDefault: true },
  { code: 'inst', name: 'Instrumentation Engineering', categoryCode: 'electronics', sortOrder: 140, engineeringDefault: true },
  { code: 'vlsi', name: 'VLSI Engineering', categoryCode: 'electronics', sortOrder: 150, engineeringDefault: true },
  { code: 'ee', name: 'Electrical Engineering', categoryCode: 'electrical', sortOrder: 160, engineeringDefault: true },
  { code: 'eee', name: 'Electrical & Electronics Engineering', categoryCode: 'electrical', sortOrder: 170, engineeringDefault: true },
  { code: 'power', name: 'Power Engineering', categoryCode: 'electrical', sortOrder: 180, engineeringDefault: true },
  { code: 'me', name: 'Mechanical Engineering', categoryCode: 'mechanical', sortOrder: 190, engineeringDefault: true },
  { code: 'prod', name: 'Production Engineering', categoryCode: 'mechanical', sortOrder: 200, engineeringDefault: true },
  { code: 'mfg', name: 'Manufacturing Engineering', categoryCode: 'mechanical', sortOrder: 210, engineeringDefault: true },
  { code: 'ie', name: 'Industrial Engineering', categoryCode: 'mechanical', sortOrder: 220, engineeringDefault: true },
  { code: 'mechatronics', name: 'Mechatronics', categoryCode: 'mechanical', sortOrder: 230, engineeringDefault: true },
  { code: 'civil', name: 'Civil Engineering', categoryCode: 'civil', sortOrder: 240, engineeringDefault: true },
  { code: 'construction', name: 'Construction Engineering', categoryCode: 'civil', sortOrder: 250, engineeringDefault: true },
  { code: 'structural', name: 'Structural Engineering', categoryCode: 'civil', sortOrder: 260, engineeringDefault: true },
  { code: 'chem', name: 'Chemical Engineering', categoryCode: 'chemical', sortOrder: 270, engineeringDefault: true },
  { code: 'petro', name: 'Petrochemical Engineering', categoryCode: 'chemical', sortOrder: 280, engineeringDefault: true },
  { code: 'robotics', name: 'Robotics', categoryCode: 'emerging', sortOrder: 290, engineeringDefault: true },
  { code: 'automation', name: 'Automation', categoryCode: 'emerging', sortOrder: 300, engineeringDefault: true },
  { code: 'iot', name: 'Internet of Things', categoryCode: 'emerging', sortOrder: 310, engineeringDefault: true },
  { code: 'cyber', name: 'Cyber Security', categoryCode: 'emerging', sortOrder: 320, engineeringDefault: true },
  { code: 'cloud', name: 'Cloud Computing', categoryCode: 'emerging', sortOrder: 330, engineeringDefault: true },
  { code: 'blockchain', name: 'Blockchain Technology', categoryCode: 'emerging', sortOrder: 340, engineeringDefault: true },
  { code: 'mba_mkt', name: 'Marketing', categoryCode: 'management', sortOrder: 400 },
  { code: 'mba_fin', name: 'Finance', categoryCode: 'management', sortOrder: 410 },
  { code: 'mba_hr', name: 'Human Resources', categoryCode: 'management', sortOrder: 420 },
  { code: 'mba_ops', name: 'Operations', categoryCode: 'management', sortOrder: 430 },
  { code: 'mba_ib', name: 'International Business', categoryCode: 'management', sortOrder: 440 },
  { code: 'mba_scm', name: 'Supply Chain Management', categoryCode: 'management', sortOrder: 450 },
  { code: 'mba_retail', name: 'Retail Management', categoryCode: 'management', sortOrder: 460 },
  { code: 'mba_ent', name: 'Entrepreneurship', categoryCode: 'management', sortOrder: 470 },
  { code: 'mba_ba', name: 'Business Analytics', categoryCode: 'management', sortOrder: 480 },
  { code: 'mba_itm', name: 'Information Technology Management', categoryCode: 'management', sortOrder: 490 },
  { code: 'mba_hcm', name: 'Healthcare Management', categoryCode: 'management', sortOrder: 500 },
  { code: 'mba_dm', name: 'Digital Marketing', categoryCode: 'management', sortOrder: 510 },
  { code: 'accounting', name: 'Accounting', categoryCode: 'commerce', sortOrder: 600 },
  { code: 'finance_com', name: 'Finance', categoryCode: 'commerce', sortOrder: 610 },
  { code: 'taxation', name: 'Taxation', categoryCode: 'commerce', sortOrder: 620 },
  { code: 'banking', name: 'Banking', categoryCode: 'commerce', sortOrder: 630 },
  { code: 'insurance', name: 'Insurance', categoryCode: 'commerce', sortOrder: 640 },
  { code: 'fin_markets', name: 'Financial Markets', categoryCode: 'commerce', sortOrder: 650 },
  { code: 'physics', name: 'Physics', categoryCode: 'sciences', sortOrder: 700 },
  { code: 'chemistry', name: 'Chemistry', categoryCode: 'sciences', sortOrder: 710 },
  { code: 'math', name: 'Mathematics', categoryCode: 'sciences', sortOrder: 720 },
  { code: 'stats', name: 'Statistics', categoryCode: 'sciences', sortOrder: 730 },
  { code: 'biotech', name: 'Biotechnology', categoryCode: 'sciences', sortOrder: 740 },
  { code: 'biochem', name: 'Biochemistry', categoryCode: 'sciences', sortOrder: 750 },
  { code: 'microbio', name: 'Microbiology', categoryCode: 'sciences', sortOrder: 760 },
  { code: 'genetics', name: 'Genetics', categoryCode: 'sciences', sortOrder: 770 },
  { code: 'cs_degree', name: 'Computer Science', categoryCode: 'cs_it', sortOrder: 780 },
  { code: 'english', name: 'English', categoryCode: 'arts_hum', sortOrder: 800 },
  { code: 'economics', name: 'Economics', categoryCode: 'arts_hum', sortOrder: 810 },
  { code: 'psychology', name: 'Psychology', categoryCode: 'arts_hum', sortOrder: 820 },
  { code: 'pharmacy', name: 'Pharmacy', categoryCode: 'pharmacy', sortOrder: 900 },
  { code: 'pharmacology', name: 'Pharmacology', categoryCode: 'pharmacy', sortOrder: 910 },
  { code: 'corporate_law', name: 'Corporate Law', categoryCode: 'law', sortOrder: 1000 },
  { code: 'cyber_law', name: 'Cyber Law', categoryCode: 'law', sortOrder: 1010 },
  { code: 'graphic_design', name: 'Graphic Design', categoryCode: 'design', sortOrder: 1100 },
  { code: 'ux_design', name: 'UX Design', categoryCode: 'design', sortOrder: 1110 },
];

/** @type {Array<{ code: string, name: string, disciplineCode?: string, sortOrder?: number }>} */
const TAXONOMY_SPECIALIZATIONS = [
  { code: 'ai', name: 'Artificial Intelligence', disciplineCode: 'cse', sortOrder: 10 },
  { code: 'ml', name: 'Machine Learning', disciplineCode: 'cse', sortOrder: 20 },
  { code: 'ds', name: 'Data Science', disciplineCode: 'cse', sortOrder: 30 },
  { code: 'cyber', name: 'Cyber Security', disciplineCode: 'cse', sortOrder: 40 },
  { code: 'cloud', name: 'Cloud Computing', disciplineCode: 'cse', sortOrder: 50 },
  { code: 'devops', name: 'DevOps', disciplineCode: 'cse', sortOrder: 60 },
  { code: 'blockchain', name: 'Blockchain', disciplineCode: 'cse', sortOrder: 70 },
  { code: 'fullstack', name: 'Full Stack Development', disciplineCode: 'cse', sortOrder: 80 },
  { code: 'iot', name: 'IoT', disciplineCode: 'cse', sortOrder: 90 },
  { code: 'arvr', name: 'AR/VR', disciplineCode: 'cse', sortOrder: 100 },
  { code: 'embedded', name: 'Embedded Systems', disciplineCode: 'ece', sortOrder: 110 },
  { code: 'vlsi', name: 'VLSI', disciplineCode: 'ece', sortOrder: 120 },
  { code: 'signal', name: 'Signal Processing', disciplineCode: 'ece', sortOrder: 130 },
  { code: 'comm_systems', name: 'Communication Systems', disciplineCode: 'ece', sortOrder: 140 },
  { code: 'robotics', name: 'Robotics', disciplineCode: 'me', sortOrder: 150 },
  { code: 'automobile', name: 'Automobile Engineering', disciplineCode: 'me', sortOrder: 160 },
  { code: 'thermal', name: 'Thermal Engineering', disciplineCode: 'me', sortOrder: 170 },
  { code: 'cadcam', name: 'CAD/CAM', disciplineCode: 'me', sortOrder: 180 },
  { code: 'inv_banking', name: 'Investment Banking', disciplineCode: 'mba_fin', sortOrder: 200 },
  { code: 'fin_analytics', name: 'Financial Analytics', disciplineCode: 'mba_fin', sortOrder: 210 },
  { code: 'fintech', name: 'FinTech', disciplineCode: 'mba_fin', sortOrder: 220 },
  { code: 'digital_mkt', name: 'Digital Marketing', disciplineCode: 'mba_mkt', sortOrder: 230 },
  { code: 'brand_mgmt', name: 'Brand Management', disciplineCode: 'mba_mkt', sortOrder: 240 },
  { code: 'sales_mgmt', name: 'Sales Management', disciplineCode: 'mba_mkt', sortOrder: 250 },
  { code: 'auditing', name: 'Auditing', disciplineCode: 'accounting', sortOrder: 300 },
  { code: 'tax_spec', name: 'Taxation', disciplineCode: 'taxation', sortOrder: 310 },
  { code: 'fin_analysis', name: 'Financial Analysis', disciplineCode: 'finance_com', sortOrder: 320 },
];

/** @type {Array<{ code: string, name: string, sortOrder?: number, engineeringDefault?: boolean }>} */
const TAXONOMY_ELIGIBILITY_GROUPS = [
  { code: 'computer_science', name: 'Computer Science', sortOrder: 10, engineeringDefault: true },
  { code: 'electronics', name: 'Electronics', sortOrder: 20, engineeringDefault: true },
  { code: 'electrical', name: 'Electrical', sortOrder: 30, engineeringDefault: true },
  { code: 'mechanical', name: 'Mechanical', sortOrder: 40, engineeringDefault: true },
  { code: 'civil', name: 'Civil', sortOrder: 50, engineeringDefault: true },
  { code: 'chemical', name: 'Chemical', sortOrder: 60, engineeringDefault: true },
  { code: 'management', name: 'Management', sortOrder: 70 },
  { code: 'commerce', name: 'Commerce', sortOrder: 80 },
  { code: 'sciences', name: 'Sciences', sortOrder: 90 },
  { code: 'pharmacy', name: 'Pharmacy', sortOrder: 100 },
  { code: 'law', name: 'Law', sortOrder: 110 },
  { code: 'design', name: 'Design', sortOrder: 120 },
];

/** @type {Array<{ code: string, displayName: string, degreeCode: string, disciplineCode: string, specializationCode?: string, eligibilityGroupCode: string, aliases?: string[], engineeringDefault?: boolean, sortOrder?: number }>} */
const TAXONOMY_ACADEMIC_PROGRAMS = [
  {
    code: 'btech_cse',
    displayName: 'B.Tech Computer Science Engineering',
    degreeCode: 'btech',
    disciplineCode: 'cse',
    eligibilityGroupCode: 'computer_science',
    aliases: ['CSE', 'Computer Science', 'Computer Science & Engineering'],
    engineeringDefault: true,
    sortOrder: 10,
  },
  {
    code: 'btech_cse_ai',
    displayName: 'B.Tech CSE (Artificial Intelligence)',
    degreeCode: 'btech',
    disciplineCode: 'cse',
    specializationCode: 'ai',
    eligibilityGroupCode: 'computer_science',
    aliases: ['CSE (AI)', 'CSE AI'],
    engineeringDefault: true,
    sortOrder: 20,
  },
  {
    code: 'btech_cse_aiml',
    displayName: 'B.Tech CSE (AI & ML)',
    degreeCode: 'btech',
    disciplineCode: 'aiml',
    eligibilityGroupCode: 'computer_science',
    aliases: ['CSE (AI & ML)', 'AIML'],
    engineeringDefault: true,
    sortOrder: 30,
  },
  {
    code: 'btech_cse_ds',
    displayName: 'B.Tech CSE (Data Science)',
    degreeCode: 'btech',
    disciplineCode: 'ds',
    eligibilityGroupCode: 'computer_science',
    aliases: ['CSE (Data Science)', 'CSE DS'],
    engineeringDefault: true,
    sortOrder: 40,
  },
  {
    code: 'btech_cse_cyber',
    displayName: 'B.Tech CSE (Cyber Security)',
    degreeCode: 'btech',
    disciplineCode: 'cse',
    specializationCode: 'cyber',
    eligibilityGroupCode: 'computer_science',
    aliases: ['CSE Cyber Security'],
    engineeringDefault: true,
    sortOrder: 45,
  },
  {
    code: 'btech_it',
    displayName: 'B.Tech Information Technology',
    degreeCode: 'btech',
    disciplineCode: 'it',
    eligibilityGroupCode: 'computer_science',
    aliases: ['IT'],
    engineeringDefault: true,
    sortOrder: 50,
  },
  {
    code: 'btech_ce',
    displayName: 'B.Tech Computer Engineering',
    degreeCode: 'btech',
    disciplineCode: 'ce',
    eligibilityGroupCode: 'computer_science',
    aliases: ['Computer Engineering'],
    engineeringDefault: true,
    sortOrder: 55,
  },
  {
    code: 'be_cse',
    displayName: 'B.E. Computer Science Engineering',
    degreeCode: 'be',
    disciplineCode: 'cse',
    eligibilityGroupCode: 'computer_science',
    aliases: ['BE CSE'],
    engineeringDefault: true,
    sortOrder: 60,
  },
  {
    code: 'btech_ece',
    displayName: 'B.Tech Electronics & Communication Engineering',
    degreeCode: 'btech',
    disciplineCode: 'ece',
    eligibilityGroupCode: 'electronics',
    aliases: ['ECE'],
    engineeringDefault: true,
    sortOrder: 100,
  },
  {
    code: 'btech_eee',
    displayName: 'B.Tech Electrical & Electronics Engineering',
    degreeCode: 'btech',
    disciplineCode: 'eee',
    eligibilityGroupCode: 'electrical',
    aliases: ['EEE'],
    engineeringDefault: true,
    sortOrder: 110,
  },
  {
    code: 'btech_ee',
    displayName: 'B.Tech Electrical Engineering',
    degreeCode: 'btech',
    disciplineCode: 'ee',
    eligibilityGroupCode: 'electrical',
    aliases: ['EE'],
    engineeringDefault: true,
    sortOrder: 115,
  },
  {
    code: 'btech_me',
    displayName: 'B.Tech Mechanical Engineering',
    degreeCode: 'btech',
    disciplineCode: 'me',
    eligibilityGroupCode: 'mechanical',
    aliases: ['ME'],
    engineeringDefault: true,
    sortOrder: 120,
  },
  {
    code: 'btech_civil',
    displayName: 'B.Tech Civil Engineering',
    degreeCode: 'btech',
    disciplineCode: 'civil',
    eligibilityGroupCode: 'civil',
    engineeringDefault: true,
    sortOrder: 130,
  },
  {
    code: 'btech_chem',
    displayName: 'B.Tech Chemical Engineering',
    degreeCode: 'btech',
    disciplineCode: 'chem',
    eligibilityGroupCode: 'chemical',
    engineeringDefault: true,
    sortOrder: 140,
  },
  {
    code: 'btech_robotics',
    displayName: 'B.Tech Robotics',
    degreeCode: 'btech',
    disciplineCode: 'robotics',
    eligibilityGroupCode: 'mechanical',
    engineeringDefault: true,
    sortOrder: 150,
  },
  {
    code: 'diploma_cse',
    displayName: 'Diploma Computer Science Engineering',
    degreeCode: 'diploma_engineering',
    disciplineCode: 'cse',
    eligibilityGroupCode: 'computer_science',
    engineeringDefault: true,
    sortOrder: 160,
  },
  {
    code: 'mtech_cse',
    displayName: 'M.Tech Computer Science Engineering',
    degreeCode: 'mtech',
    disciplineCode: 'cse',
    eligibilityGroupCode: 'computer_science',
    engineeringDefault: true,
    sortOrder: 200,
  },
  {
    code: 'mtech_ece',
    displayName: 'M.Tech Electronics & Communication Engineering',
    degreeCode: 'mtech',
    disciplineCode: 'ece',
    eligibilityGroupCode: 'electronics',
    engineeringDefault: true,
    sortOrder: 210,
  },
  {
    code: 'mca',
    displayName: 'MCA',
    degreeCode: 'mca',
    disciplineCode: 'cs_degree',
    eligibilityGroupCode: 'computer_science',
    engineeringDefault: true,
    sortOrder: 220,
  },
  {
    code: 'mba_finance',
    displayName: 'MBA Finance',
    degreeCode: 'mba',
    disciplineCode: 'mba_fin',
    eligibilityGroupCode: 'management',
    sortOrder: 300,
  },
  {
    code: 'mba_marketing',
    displayName: 'MBA Marketing',
    degreeCode: 'mba',
    disciplineCode: 'mba_mkt',
    eligibilityGroupCode: 'management',
    sortOrder: 310,
  },
  {
    code: 'bca',
    displayName: 'BCA',
    degreeCode: 'bca',
    disciplineCode: 'cs_degree',
    eligibilityGroupCode: 'computer_science',
    sortOrder: 320,
  },
  {
    code: 'bcom',
    displayName: 'B.Com',
    degreeCode: 'bcom',
    disciplineCode: 'accounting',
    eligibilityGroupCode: 'commerce',
    sortOrder: 330,
  },
  {
    code: 'bpharm',
    displayName: 'B.Pharm',
    degreeCode: 'bpharm',
    disciplineCode: 'pharmacy',
    eligibilityGroupCode: 'pharmacy',
    sortOrder: 340,
  },
];

const ENGINEERING_COLLEGE_TAXONOMY_DEFAULTS = {
  institutionProfile: 'engineering',
  usePlatformDefaults: true,
  defaultDegreeCode: 'btech',
  defaultProgramCode: 'btech_cse',
  defaultEligibilityGroupCodes: [
    'computer_science',
    'electronics',
    'electrical',
    'mechanical',
    'civil',
    'chemical',
  ],
  restrictProgramsToDefaults: true,
};

const GENERAL_COLLEGE_TAXONOMY_DEFAULTS = {
  institutionProfile: 'general',
  usePlatformDefaults: false,
  defaultDegreeCode: 'btech',
  defaultProgramCode: null,
  defaultEligibilityGroupCodes: [],
  restrictProgramsToDefaults: false,
};

module.exports = {
  TAXONOMY_DEGREE_LEVELS,
  TAXONOMY_DEGREES,
  TAXONOMY_DISCIPLINE_CATEGORIES,
  TAXONOMY_DISCIPLINES,
  TAXONOMY_SPECIALIZATIONS,
  TAXONOMY_ELIGIBILITY_GROUPS,
  TAXONOMY_ACADEMIC_PROGRAMS,
  ENGINEERING_COLLEGE_TAXONOMY_DEFAULTS,
  GENERAL_COLLEGE_TAXONOMY_DEFAULTS,
};
