/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');

const colleges = [
  {
    id: 'a1000000-0000-0000-0000-000000000001',
    nirf_rank: 1,
    accreditation: 'UGC, AICTE',
    naac_grade: 'A++',
    showcase: {
      nbaAccreditedPrograms: 'CSE, ECE, Mechanical (Tier-1)',
      nirfCategoryRanks: 'Overall #1, Engineering #1, Innovation #2',
      notableAlumni: 'Sundar Pichai, Arvind Krishna, Kris Gopalakrishnan',
      patentCount: 820,
      startupCount: 310,
      incubationCells: 'IITM Incubation Cell, IITM Research Park',
      researchCenters: 'AI4Bharat, Center for NEMS, National Center for Combustion R&D',
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000002',
    nirf_rank: 9,
    accreditation: 'UGC, AICTE',
    naac_grade: 'A+',
    showcase: {
      nbaAccreditedPrograms: 'CSE, ECE, EEE, Civil, Mechanical',
      nirfCategoryRanks: 'Engineering Top-10, Architecture Top-25',
      notableAlumni: 'N. Chandrasekaran, S. Venkatachary, M. Lakshmanan',
      patentCount: 240,
      startupCount: 95,
      incubationCells: 'NIT Trichy Incubation & Entrepreneurship Hub',
      researchCenters: 'Energy & Environment, Robotics, Materials & Manufacturing',
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000003',
    nirf_rank: 25,
    accreditation: 'UGC, AICTE',
    naac_grade: 'A+',
    showcase: {
      nbaAccreditedPrograms: 'CSE, ECE, EEE, Chemical, Mechanical',
      nirfCategoryRanks: 'University Top-30, Engineering Top-30',
      notableAlumni: 'Sanjay Mehrotra, Prithviraj Chavan, Baba Kalyani',
      patentCount: 310,
      startupCount: 180,
      incubationCells: 'BITS BioCyTiH Foundation, PIEDE Society',
      researchCenters: 'Photonics, Data Science, Advanced Materials',
    },
  },
];

function sqlString(v) {
  return `'${String(v).replace(/'/g, "''")}'`;
}

const lines = [];
lines.push('-- Generated by scripts/generate_college_showcase_seed.js');
for (const c of colleges) {
  lines.push(`UPDATE tenants
SET nirf_rank = ${Number(c.nirf_rank)},
    accreditation = ${sqlString(c.accreditation)},
    naac_grade = ${sqlString(c.naac_grade)},
    settings = jsonb_set(
      COALESCE(settings, '{}'::jsonb),
      '{institutionShowcase}',
      ${sqlString(JSON.stringify(c.showcase))}::jsonb,
      true
    ),
    updated_at = NOW()
WHERE id = ${sqlString(c.id)}::uuid;`);
  lines.push('');
}

const outPath = path.join(__dirname, '..', 'db', 'seeds', 'college_showcase_updates.sql');
fs.writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
console.log(`Wrote ${outPath}`);
